confirm_profile_update_link:
    path: /vendor/profile-update/{token}
    methods: [GET]
    defaults:
        _controller: bitbag.open_marketplace.component.core.vendor.controller.profile.confirm_update
        _sylius:
            template: "Context/Vendor/Profile/update.html.twig"
            form: BitBag\OpenMarketplace\Component\Core\Vendor\Form\Type\Profile\ProfileType
            event: update
            repository:
                method: findOneByActivationToken
                arguments:
                    token: $token
