imports:
    - { resource: "../../src/Component/Core/Admin/Resources/config.yaml" }
    - { resource: "../../src/Component/Core/Common/Resources/config.yaml" }
    - { resource: "../../src/Component/Core/Shop/Resources/config.yaml" }
    - { resource: "../../src/Component/Core/Vendor/Resources/config.yaml" }
    - { resource: "../../src/Component/Override/Resources/config.yaml" }
