framework:
    validation:
        enable_annotations: true
        mapping:
            paths:
            - '%kernel.project_dir%/src/Component/Core/Resources/validation/'
            - '%kernel.project_dir%/src/Api/Resources/validation/'
            - '%kernel.project_dir%/src/Component/ProductListing/Resources/validation/'
            - '%kernel.project_dir%/src/Component/Vendor/Resources/validation/'
