app_admin:
    resource: 'routing/admin.yml'
    prefix: /admin
app_shop:
    resource: 'routing/shop.yml'
    prefix: /{_locale}
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

sylius_shop_checkout_complete:
    resource: 'routing/shop/order.yml'
    prefix: /{_locale}

conversation:
  resource: "routing/conversation.yml"

conversation_category:
    resource: "routing/admin/conversation_category.yml"

