sylius_resource:
    resources:
        open_marketplace.draft_attribute:
            classes:
                model: BitBag\OpenMarketplace\Component\ProductListing\Entity\DraftAttribute
                interface: BitBag\OpenMarketplace\Component\ProductListing\Entity\DraftAttributeInterface
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                repository: BitBag\OpenMarketplace\Component\ProductListing\Repository\DraftAttributeRepository
                form: BitBag\OpenMarketplace\Component\Core\Vendor\Form\Type\ProductListing\DraftAttributeType
            translation:
                classes:
                    model: BitBag\OpenMarketplace\Component\ProductListing\Entity\DraftAttributeTranslation
        open_marketplace.draft_attribute_value:
            classes:
                model: BitBag\OpenMarketplace\Component\ProductListing\Entity\DraftAttributeValue
