open_marketplace_vendor_shop_page_index:
    path: /{_locale}/vendors/{vendor_slug}
    methods: [GET]
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            template: "Context/Vendor/VendorPage/index.html.twig"
            grid: open_marketplace_vendor_shop_product

open_marketplace_vendor_shop_product_index:
    path: /{_locale}/vendors/{vendor_slug}/taxons/{slug}
    methods: [GET]
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
        slug: .+(?<!/)
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            template: "Context/Vendor/VendorPage/index.html.twig"
            grid: open_marketplace_vendor_shop_product

open_marketplace_shop_partial_taxon_show_by_slug:
    path: /{_locale}/vendors/{vendor_slug}/by-slug/{slug}
    methods: [GET]
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
        slug: .+
    defaults:
        _controller: sylius.controller.taxon:showAction
        _sylius:
            template: $template
            repository:
                method: findOneBySlug
                arguments:
                    - $slug
                    - "expr:service('sylius.context.locale').getLocaleCode()"

sylius_shop_checkout_complete:
    path: /{_locale}/checkout/complete
    methods: [GET, PUT]
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
    defaults:
        _controller: sylius.controller.order:updateAction
        _sylius:
            event: complete
            flash: false
            template: '@SyliusShop/Checkout/complete.html.twig'
            repository:
                method: find
                arguments:
                    - "expr:service('sylius.context.cart').getCart()"
            state_machine:
                graph: sylius_order_checkout
                transition: complete
            redirect:
                route: sylius_shop_order_pay
                parameters:
                    tokenValue: resource.tokenValue
            form:
                type: Sylius\Bundle\CoreBundle\Form\Type\Checkout\CompleteType
                options:
                    validation_groups: 'sylius_checkout_complete'

sylius_shop_account_order_index:
    path: /{_locale}/account/orders
    methods: [GET]
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
    defaults:
        _controller: sylius.controller.order:indexAction
        _sylius:
            section: shop_account
            template: "@SyliusShop/Account/Order/index.html.twig"
            grid: open_marketplace_account_order

sylius_shop_account_order_show:
    path: /{_locale}/account/orders/{number}
    methods: [GET]
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
    defaults:
        _controller: sylius.controller.order:showAction
        _sylius:
            section: shop_account
            template: "@SyliusShop/Account/Order/show.html.twig"
            repository:
                method: findOneByNumberAndCustomer
                arguments:
                    - $number
                    - "expr:service('sylius.context.customer').getCustomer()"

sylius_shop_checkout_select_shipping:
    path: /{_locale}/checkout/select-shipping
    methods: [GET, PUT]
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
    defaults:
        _controller: sylius.controller.order:updateAction
        _sylius:
            event: select_shipping
            flash: false
            template: "Context/Shop/Checkout/selectShipping.html.twig"
            form: BitBag\OpenMarketplace\Component\Core\Shop\Form\Type\Checkout\SelectShippingType
            repository:
                method: findCartForSelectingShipping
                arguments:
                    - "expr:service('sylius.context.cart').getCart().getId()"
            state_machine:
                graph: sylius_order_checkout
                transition: select_shipping

sylius_shop_order_thank_you:
    path: /{_locale}/thank-you
    methods: [GET]
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
    defaults:
        _controller: open_marketplace.controller.order.order_controller:thankYouAction
        _sylius:
            template: "Context/Shop/Checkout/thankYou.html.twig"
