open_marketplace_shop_account:
    resource: "routing/account.yaml"

open_marketplace_shop_checkout:
    resource: "routing/checkout.yaml"

open_marketplace_shop_vendor_page:
    resource: "routing/vendor_page.yaml"
